pqr_file: ZIKV_6CO8_aa_charge_vdw_addspace.pqr
face_file: surf_gs1.0_noter_split.face
vert_file: surf_gs1.0_noter_split.vert
regular: 2
expansion_order: 4
ncrit: 500
ep_in: 4.
ep_ex: 80.
kappa: 0.125
tol: 1.e-4
restart: 400
save_solution: 1
